name: Publish

on:
  push:
    tags:
      - v[0-9]*.[0-9]*.[0-9]*

jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-${{ hashFiles('package-lock.json') }}
            npm-
      - run: npm ci && npm ci --prefix cli
      - run: npm run bundle
      - name: Store bundle artifact
        uses: actions/upload-artifact@v3
        with:
          name: bundles
          path: bundles
          retention-days: 1
  publish:
    name: Publish to NPM
    needs: [bundle]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - uses: actions/checkout@v3
      - name: Download bundled artifacts
        uses: actions/download-artifact@v3
        with:
          name: bundles
          path: bundles
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-${{ hashFiles('package-lock.json') }}
            npm-
      - name: Before deploy
        run: npm ci && npm run declarations
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
