name: Publish to NPM

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        name: 'Setup Node'
        with:
          node-version: '14.x'
          registry-url: https://registry.npmjs.org/
          scope: '@ioxio'
      - run: npm ci
        name: 'Install dependencies'
      - run: npm publish --access public
        name: 'Publish to NPM'
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
